CREATE TABLE  pipeline_runs(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    dag_name VARCHAR(50) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    duration INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retries INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    constraint pk_pipeline PRIMARY KEY(id)
);

CREATE TABLE model_inference(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    model_name VARCHAR(50) NOT NULL,
    label VARCHAR(50) NOT NULL,
    latency_ms FLOAT NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    
    constraint pk_model PRIMARY KEY (id)
);
CREATE TABLE api_requests(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    endpoint VARCHAR(50) NOT NULL,
    method VARCHAR(50) NOT NULL,
    status_code INT NOT NULL,
    response_time_ms FLOAT NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    
    constraint pk_api PRIMARY KEY (id) 
);